% Script generated by Brainstorm (01-Oct-2020)

% Input files
sFiles = {...
    'sub02/run_tsss_notch/data_B_trial001.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Band-pass:13Hz-14Hz
sFiles = bst_process('CallProcess', 'process_bandpass', sFiles, [], ...
    'sensortypes', 'MEG, EEG', ...
    'highpass',    13, ...
    'lowpass',     14, ...
    'tranband',    0, ...
    'attenuation', 'strict', ...  % 60dB
    'ver',         '2019', ...  % 2019
    'mirror',      0, ...
    'overwrite',   0);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

